services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony-php
    working_dir: /var/www/app
    user: "1002:1002"
    volumes:
      - ./app:/var/www/app
      - ./app/var/cache:/var/www/app/var/cache
      - ./app/var/log:/var/www/app/var/
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony?charset=utf8mb4"
      
      # APIS EXTERNES
      OPENWEATHER_API_KEY: 1dc5842652fb1d26d080caa0818b49e7
      NEWS_API_KEY: 3dc140c900e142d68d39a620b11ded52
    depends_on:
      - db

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony-nginx
    ports:
      - "19080:80"
    volumes:
      - ./app/public:/var/www/app/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: symfony-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3407:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: symfony-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: symfony
      PMA_PASSWORD: symfony
      PMA_ABSOLUTE_URI: http://51.178.38.171:8081/
    ports:
      - "19081:80"
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: symfony-mailhog
    ports:
      - "19025:8025"
      - "12025:1025"

volumes:
  db_data: